replicaCount: 1

image:
  tag: develop-f742520
  pullPolicy: Always

ingress:
  host: fincontrol-test.jcrlabs.net

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

hpa:
  minReplicas: 1
  maxReplicas: 2
